logLevel = "DEBUG"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]
[frontends]
  [frontends.oidc-server]
  backend = "oidc-server"
  passHostHeader = true
    [frontends.oidc-server.routes.host]
    rule = "Host:oidc-server.test"
  
  [frontends.oidc-client-hybrid]
  backend = "oidc-client-hybrid"
  passHostHeader = true
    [frontends.oidc-client-hybrid.routes.host]
    rule = "Host:oidc-client-hybrid.test"
  
  [frontends.oidc-client-js]
  backend = "oidc-client-js"
  passHostHeader = true
    [frontends.oidc-client-js.routes.host]
    rule = "Host:oidc-client-js.test"
  
  [frontends.oauth2-resources-aspnetcore]
  backend = "oauth2-resources-aspnetcore"
  passHostHeader = true
    [frontends.oauth2-resources-aspnetcore.routes.host]
    rule = "Host:oauth2-resources-aspnetcore.test"

  [frontends.oauth2-client-aspnetcore]
  backend = "oauth2-client-aspnetcore"
  passHostHeader = true
    [frontends.oauth2-client-aspnetcore.routes.host]
    rule = "Host:oauth2-client-aspnetcore.test"


[backends]
  [backends.oidc-server]
    [backends.oidc-server.servers.server1]
    url = "http://oidc-server.test"

  [backends.oidc-client-hybrid]
    [backends.oidc-client-hybrid.servers.server1]
    url = "http://oidc-client-hybrid.test"

  [backends.oidc-client-js]
    [backends.oidc-client-js.servers.server1]
    url = "http://oidc-client-js.test"

  [backends.oauth2-resources-aspnetcore]
    [backends.oauth2-resources-aspnetcore.servers.server1]
    url = "http://oauth2-resources-aspnetcore.test"

  [backends.oauth2-client-aspnetcore]
    [backends.oauth2-client-aspnetcore.servers.server1]
    url = "http://oauth2-client-aspnetcore.test"
