server:
  port: 80

spring:
  application:
    name: api

  security: # https://docs.spring.io/spring-security/site/docs/current/reference/html5
    oauth2:
      resourceserver: # https://docs.spring.io/spring-security/site/docs/current/reference/html5/#webflux-oauth2-resource-server
        jwt:
          issuer-uri: http://oidc-server.test
